Refactor: Use Crypto package for UUID's instead of uuid
joinself/self-typescript-sdk pull request #188
Opened 2023-01-09 16:53 UTC by WillKirkmanM

NodeJS Contains a built-in randomUUID function which generates v4 UUID's meaning we can remove the UUID dependency.

2023-02-13 09:26 UTC, adriacidre requested changes
hey @WillKirkmanM thanks for your contribution. 
Pull request looks good, even I left a small cleanup comment to remove the import of `Hash`.

2023-02-13 09:26 UTC, adriacidre commented on src/chat-service.ts
> +import { randomUUID as uuidv4, Hash } from 'crypto';
As far as I can see even `Hash` was imported it doesn't seem to be used on this service. I think we should try to remove it, and check if tests are still passing.

2023-02-13 12:15 UTC, WillKirkmanM commented on src/chat-service.ts
> +import { randomUUID as uuidv4, Hash } from 'crypto';
Got it! Will do that now.

2023-03-15 10:46 UTC, adriacidre approved these changes
Thanks mate, good stuff

2023-03-15 10:46 UTC, merged